Repository ZEISS/ca-injector, pull requests merged in 2024-04, with the labels that each got.

#12 remove branch trigger
  .github/workflows/version_bump.yml
Labels: helm-patch, app-major

#13 install via apt, fix label name
  .github/workflows/version_bump.yml
Labels: helm-patch, app-major

#14 use steps inside one job
  .github/workflows/version_bump.yml
Labels: helm-patch, app-major

#15 fix var reference
  .github/workflows/version_bump.yml
Labels: helm-minor, app-major

#16 remove manual git tag being required
  .github/workflows/app_release.yml
  .github/workflows/docker.yml
  .github/workflows/version_bump.yml
  README.md
Labels: helm-minor

#18 describe workflow
  README.md
Labels: helm-patch, app-patch

#10 fix docker tag
  .github/workflows/app_release.yml
  .github/workflows/docker.yml
  .github/workflows/version_bump.yml
  README.md
  charts/ca-injector/Chart.yaml
Labels: helm-minor, app-minor

#22 Configure git for helm chart release action
  .github/workflows/helm.yml
Labels: helm-minor, app-minor

#24 fix inheritance of event.name
  .github/workflows/docker.yml
Labels: automatic_app_release

#26 Task/app patch
  .github/workflows/app_release.yml
  .github/workflows/docker.yml
  .github/workflows/version_bump.yml
  README.md
Labels: helm-patch, app-patch

#30 Use specific ref for trivy scan on release
  .github/workflows/docker.yml
Labels: helm-minor, app-minor
